name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  perl:

    strategy:
      matrix:
        perl-version: ['520','524','526']
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    container:
      image: centos/perl-${{ matrix.perl-version }}-centos7

    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: perl -V
      run: |
        perl -V

    - name: Install Dependencies
      run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure

    - name: Tesing
      run: |
        prove -l t